// Code generated by command: go run gen.go -out ../decodeblock.s -stubs ../decodeblock_arm64.go -arch arm64 -arm64gen -widemove -decoderonly -pkg=minlz. DO NOT EDIT.

//go:build !appengine && !noasm && gc && !purego

package minlz

// decodeBlockAsmLowered encodes a non-empty src to a guaranteed-large-enough dst.
// It assumes that the varint-encoded length of the decompressed bytes has already been read.
//
//go:noescape
func decodeBlockAsmLowered(dst []byte, src []byte) int
